server:
  port: 8989
spring:
  application:
    name: USER-SERVICE
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  boot:
    admin:
      client:
        url: http://localhost:8081
        instance:
          management-base-url: http://localhost:8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  file:
    name: E:/ecommerce/micro/log/micro.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
